- hosts: all

  gather_facts: no
  become: yes

  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/vagrant

  roles:
    - web_server

  handlers:
    - include: roles/web_server/handlers/main.yml
