- hosts: all

  gather_facts: no
  become: yes

  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/vagrant

  tasks:
    - name: install packages
      yum:
        name: "{{ item.name }}"
      with_items:
        - name: httpd
        - name: firewalld

    - name: start services
      service:
        name: "{{ item.name }}"
        state: started
        enabled: yes
      with_items:
        - name: httpd
        - name: firewalld

    - name: configure firewalld
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      notify: restart firewalld

    # 追加
    - name: create directory
      file:
        state: directory
        path: /var/www/html/test/

    # 追加
    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html/test/index.html

    # 追加
    - name: copy httpd configure file
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart httpd


  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted

    # 追加
    - name: restart httpd
      service:
        name: httpd
        state: restarted
