- hosts: all

  gather_facts: no
  become: yes

  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/vagrant

  tasks:
    - name: install packages
      yum:
        name: "{{ item.name }}"
      with_items:
        - name: httpd
        - name: firewalld

    - name: start services
      service:
        name: "{{ item.name }}"
        state: started
        enabled: yes
      with_items:
        - name: httpd
        - name: firewalld

    - name: configure firewalld
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
